[package]
name = "RustMusic"
version = "0.1.0"
authors = ["zmant <zmant724@aliyun.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
actix-http = "0.2.4"
reqwest = { version = "0.10.0-alpha.1", features = ["json", "blocking", "cookies"] }
rand = { version = "0.7" }
base64 = "0.11"
openssl = "0.10"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures-channel-preview="0.3.0-alpha.19"
tokio = "0.2.0-alpha.6"
futures = "0.3"
urlqstring = { path = "../urlqstring" }
listenfd = "0.3"
lazy_static = "1.4"

